### ISSUE TITLE
Fix dialogue attribution tag overlap

### ISSUE THREAD

**Issue by JonathanReeve** [open-editions/corpus-joyce-dubliners-tei#3]

**Comment by JSchaeuble** [comment]
span.tag.dialog {
        border: 1px solid #A0A0C3;
        background-color: #D5D5F3;

        padding: 1px 3px 0 3px;
        font-size: smaller;

        right: 102%;
        max-width: none;
        white-space: nowrap;
    }

**Comment by JonathanReeve** [comment]
Thanks for this! Would you be willing to submit this as a PR?

**Comment by JSchaeuble** [comment]
Done, I think (I guess I gave away here that I'm not a regular GitHub user, but I suppose you noticed that before ;) )

**Comment by JonathanReeve** [comment]
Thanks! Closing this.
